--
-- PostgreSQL database dump
--

\restrict QfhQivKI7qWrbLycR2Fa28rVLXDAKGdpNRHJdSMYnoxMkjg6RobP8BF9YuPQqqP

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

-- Started on 2025-11-14 10:28:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id bigint NOT NULL,
    author character varying(255),
    title character varying(255),
    category character varying(255),
    description text,
    is_fav boolean DEFAULT false
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5009 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (id, author, title, category, description, is_fav) FROM stdin;
2	Haro Aso	Alice in Borderland, Vol. 8	Comics & Graphic Novels	Not every visitor to Borderland spends their time struggling to survive. Much like Arisu, some are hunting for the truth behind the strange and deadly world they’ve landed in. But whether that means searching for the boundaries of their strange prison or finding ways to expose Borderland to the media back home, does the truth even matter if everyone dies before they can share it? -- VIZ Media	f
1	Ali Hazelwood	The Love Hypothesis	Fiction	A stunning hardcover collector’s edition of Ali Hazelwood’s instant New York Times bestseller and TikTok sensation featuring: • A shimmering, revamped cover • Endpapers with all new art from Lilith Saur featuring Olive and Adam • STEM stenciled spredges • A sunny, foil stamped case • Fun additional chapter heading doodles throughout, and... • A brand new bonus chapter featuring THAT KISS from Adam’s point of view When a fake relationship between scientists meets the irresistible force of attraction, it throws one woman's carefully calculated theories on love into chaos. As a third-year Ph.D. candidate, Olive Smith doesn't believe in lasting romantic relationships—but her best friend does, and that's what got her into this situation. Convincing Anh that Olive is dating and well on her way to a happily ever after was always going to take more than hand-wavy Jedi mind tricks: Scientists require proof. So, like any self-respecting biologist, Olive panics and kisses the first man she sees. That man is none other than Adam Carlsen, a young hotshot professor—and well-known ass. Which is why Olive is positively floored when Stanford's reigning lab tyrant agrees to keep her charade a secret and be her fake boyfriend. But when a big science conference goes haywire, putting Olive's career on the Bunsen burner, Adam surprises her again with his unyielding support and even more unyielding...six-pack abs. Suddenly their little experiment feels dangerously close to combustion. And Olive discovers that the only thing more complicated than a hypothesis on love is putting her own heart under the microscope.	f
3	F. Scott Fitzgerald	The Great Gatsby	Fiction	Description	f
5	Frank Herbert	Dune	Sci-Fi	Description	f
4	Yuval Noah Harari	Sapiens	Non-fiction	Description for book	f
6	Joy	Good	\N	\N	f
7	Group E	Grope E	fiction	Group E	f
8	Suzanne Collins	The Hunger Games (Hunger Games, Book One)	Young Adult Fiction	This Special Edition of The Hunger Games includes the most extensive interview Suzanne Collins has given since the publication of The Hunger Games; an absorbing behind-the-scenes look at the creation of the series; and an engaging archival conversation between Suzanne Collins and YA legend Walter Dean Myers on writing about war. The Special Edition answers many questions fans have had over the years, and gives great insight into the creation of this era-defining work. In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV.Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to death before-and survival, for her, is second nature. Still, if she is to win, she will have to start making choices that weigh survival against humanity and life against love.	f
9	Group Ex	GroupEx	fiction	Group Ex	f
10	Tabo Mwewa	This is A Test Book	Fiction	Adding this book to test if it will add to database	f
11	Tabo	Group E postman book	\N	\N	f
12	AQEEL AHMED	Barbie's Lost Unicorn Quest	Juvenile Fiction	The sweet children's book "Barbie's Lost Unicorn Quest" takes place in a cute town surrounded by forests and hills. Barbie, a brave and daring young woman, and her magical horse friend Stardust are the main characters of the book. As the game goes on, Barbie and Stardust go on an adventure into the mysterious Enchanted Forest, which is full of surprises and mysteries that are hard to understand. As they meet different species that are charming, like singing flowers and talking mice, their connection with the forest grows. Their adventure takes a strange turn when they find an old, moss-covered bridge that goes to a hidden glade and a beautiful amulet with a unicorn on it. With this charm, you can start the quest that only Barbie and Stardust can finish. The Enchanted Tree, which looks out for lost unicorns, wakes up when the amulet touches it and chooses Barbie to be the chosen one. Together with Stardust, Barbie set out to find a lost horse deep in the forest. The amulet helped them along the way. As they go, they ask other people who live in the woods for advice, which emphasizes the idea of brotherhood and giving. They find Luna, the lost unicorn, bathed in silver light by the lovely stream that will take them to their last stop. Once Luna and her friends get back together, they use all of their skills to open a portal back to Hamlet, where they are made to feel very welcome. That's not the end of the story, though. In the Enchanted Forest, Barbie, Stardust, and Luna go on adventures while they work together to bring back the forest's magic. In the end, they are able to bring peace back to the forest by starting a new quest to find three old mechanical lights. Over the years, Barbie and her friends become known in town for being kind and smart, which makes them popular. The story has a lesson of wonder and hope that stresses the importance of friendship, being brave, and believing in the strange. "Barbie's Lost Unicorn Quest" is a well-known story that tells kids to value their relationships with others, enjoy nature's beauty, and stay open to the amazing things that are waiting for them. This is how the story starts: Barbie used to live in a cute town with rolling hills and lots of green trees. Barbie wasn't like other girls because she was kind and liked to try new things. Stardust, a magical horse, was Barbie's best friend and what really set her apart. Barbie and Stardust were always connected because they were friends and because they were magical everywhere they went. Stardust was beautiful to look at with his bright horn and hair. His hooves left a line of stardust behind them, and his laughter sounded like bells. When put together, they stood for the extraordinary. They laughed and went on adventures during the day. People in the town where Barbie and Stardust lived were friendly and warm, but they were aware that something strange always seemed to be present with them. In the mornings, they would explore the fields. In the afternoons, they would have picnics by the creek, and at night, they would look up at the stars. A gust of wind blew across the field one beautiful morning while Barbie and Stardust were having a picnic in their favorite spot under the shade of an old oak tree. A sheet of paper was carried by the wind. Barbie ran outside and grabbed the flying piece of paper with wide eyes. When she unfolded the paper, it showed a strange map. The complicated lines and symbols on it looked like the universe was just ready to be found. Barbie looked at the map with a racing heart. Stardust gave her a soft kiss because she could tell she was ready for an adventure. Barbie told Stardust quickly, "We need to follow this map." "It's a chance to explore the unknown and uncover the secrets of our world." Stardust agreed with a nod, and his eyes were shining with excitement. With the map in hand, they left the meadow they loved and set out on a new journey. The map led them up steep hills, through dense woods, and across sparkling streams. Every step was full of magic and wonder. Along the way, they met strange animals like talking squirrels and glowing lights that led them deeper into the unknown. Barbie and Stardust felt like they were in a fairy tale. Their friendship grew stronger every day as the magic in the woods seemed to come to life. There was a time when Barbie and Stardust found a secret glade as the sun was going down and the stars started to shine. A pretty tree with bright, shiny apples hanging from its branches stood in the middle of the glade. They saw a beautiful charm with a realistic unicorn design under the tree. When Barbie picked up the charm, her hand felt warm and tingly. Stardust gave her a soft kiss, as if to beg her to wear the charm. There was a pleasant, singing voice in the glade that seemed to come to life as she moved. Barbie and Stardust looked at each other puzzled as the Enchanted Tree sang, "Barbie, dear child, you have awakened me." The Tree then said, "I am the keeper of secrets and wonders, and you are the chosen one." Barbie and Stardust accepted their fate and set out to find the lost unicorn as the Tree sang, "In the depths of this forest lies a hidden realm, and within it resides a unicorn who has lost its wand." On their journey, they will face both difficult situations and breathtakingly beautiful scenes. They crossed interesting, suspended bridges, talked to animals that were full of wisdom, and even found a singing grove of flowers whose harmonies led them to a beautiful waterfall. "To find the lost unicorn, so rare, seek the waterfall, pure and fair, where moonbeams dance and stars alight, your friend awaits, bathed in silver light," the flowers said. Barbie gave Luna a sweet smile and said, "Don't worry." Let us help you get back to your realm. With Luna by their side, Barbie, Stardust, and Luna's magic worked together to make a portal that led them back to the village. "Thank you for finding me, dear friends. When I was following a shooting star, I got lost. My name is Luna. "I've been here ever since, unable to find my way back home," the voice of the Enchanted Tree told them. As soon as they stepped through the portal, they were back in their familiar village. When the lost unicorn was found, everyone was thrilled, and there was a lot of laughter. Barbie was additionally thrilled to learn that Luna had returned home. The unicorn Stardust had a beautiful horn that sparkled like the night sky and a mane that shimmered like silver. His hooves left a trail of stardust wherever he went, and his laughter sounded like bells. He and Barbie had been together since Barbie was a little girl. Barbie and Stardust were very close. She met him when she saw him as a little boy with big eyes. Their love was stronger than words and wen.	f
\.


--
-- TOC entry 5015 (class 0 OID 0)
-- Dependencies: 219
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 12, true);


--
-- TOC entry 4858 (class 2606 OID 16397)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 24610)
-- Name: book unique_title_author; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT unique_title_author UNIQUE (title, author);


-- Completed on 2025-11-14 10:28:46

--
-- PostgreSQL database dump complete
--

\unrestrict QfhQivKI7qWrbLycR2Fa28rVLXDAKGdpNRHJdSMYnoxMkjg6RobP8BF9YuPQqqP

